# Generated by Django 3.0.2 on 2020-01-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_short_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('scoring', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('passe', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('three_pts', models.IntegerField()),
                ('drible', models.IntegerField()),
                ('bloco', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('forca', models.IntegerField()),
                ('ressaltos', models.IntegerField()),
                ('cultura_tatica', models.IntegerField()),
                ('potencial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_short_name', models.CharField(max_length=50)),
                ('General_Manager', models.CharField(max_length=50)),
                ('Conference', models.CharField(choices=[('EC', 'Eastern Conference'), ('WC', 'Western Conference')], max_length=2)),
                ('Division', models.CharField(choices=[('NWD', 'Northwest Division'), ('PAD', 'Pacific Division'), ('SWD', 'Southwest Division'), ('ATD', 'Atlantic Division'), ('SED', 'Southeast Division'), ('CED', 'Central Division')], max_length=3)),
                ('draft_pick_season10_1stround', models.CharField(max_length=3)),
                ('draft_pick_season10_2ndround', models.CharField(max_length=3)),
                ('draft_pick_season11_1stround', models.CharField(max_length=3)),
                ('draft_pick_season11_2ndround', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='nba_simulator.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='nba_simulator.Team')),
                ('player_of_the_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_simulator.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_simulator.Team'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_season9', models.IntegerField()),
                ('contract_season10', models.IntegerField()),
                ('contract_season11', models.IntegerField()),
                ('contract_season12', models.IntegerField()),
                ('contract_season13', models.IntegerField()),
                ('contract_season14', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_simulator.Player')),
            ],
        ),
    ]
