# Generated by Django 3.0.2 on 2020-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Conference',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='General_Manager',
            new_name='general_manager',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
