# Generated by Django 3.0.2 on 2020-01-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0002_auto_20200121_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_short_name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
