# Generated by Django 3.0.2 on 2020-01-22 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0003_auto_20200122_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='general_manager_nick',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='away_team_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='player_of_the_game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nba_simulator.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, choices=[('EC', 'Eastern Conference'), ('WC', 'Western Conference')], max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, choices=[('NWD', 'Northwest Division'), ('PAD', 'Pacific Division'), ('SWD', 'Southwest Division'), ('ATD', 'Atlantic Division'), ('SED', 'Southeast Division'), ('CED', 'Central Division')], max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='draft_pick_season10_1stround',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='draft_pick_season10_2ndround',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='draft_pick_season11_1stround',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='draft_pick_season11_2ndround',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='general_manager',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
