# Generated by Django 3.0.2 on 2020-01-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0004_auto_20200122_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away_team_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_score',
            field=models.IntegerField(null=True),
        ),
    ]
