# Generated by Django 3.0.2 on 2020-01-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0005_auto_20200123_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
