# Generated by Django 3.0.2 on 2020-01-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0006_auto_20200123_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='player_of_the_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_simulator.Player'),
        ),
    ]
