# Generated by Django 3.0.2 on 2020-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0008_auto_20200123_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, upload_to='nba_simulator/static/nba_simulator/images/photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(upload_to='nba_simulator/static/nba_simulator/images/logos/'),
        ),
    ]
