# Generated by Django 3.0.2 on 2020-01-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0010_auto_20200125_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Matchup',
        ),
    ]
