# Generated by Django 3.0.2 on 2020-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0015_auto_20200326_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_season10',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_season11',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_season12',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_season13',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_season14',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_season9',
        ),
        migrations.AddField(
            model_name='contract',
            name='is_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='season',
            field=models.PositiveIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
