# Generated by Django 3.0.2 on 2020-03-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_simulator', '0016_auto_20200326_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='season',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(default='', max_length=8),
        ),
    ]
